import Image from 'next/image';
const whatsapp = 'https://wa.me/525578806465?text=Hola%2C%20quiero%20mi%20Tappia.%20Me%20gustar%C3%ADa%20recibir%20informaci%C3%B3n.';
export const metadata = { title: 'Tappia · Tu negocio, a un toque de distancia', description: 'Conecta a tus clientes con tus reseñas, redes o menú mediante una placa QR y NFC. Consulta las aperturas de tus enlaces desde Tappia.' };
export default function Home() {
  return <div className="home">
    <header className="home-nav"><a className="brand" href="/" aria-label="Tappia, inicio">tappia</a><nav aria-label="Principal"><a href="#como-funciona">Qué hacemos</a><a href="#nosotros">Quiénes somos</a><a href="#contacto">Contacto</a><a className="nav-login" href="/admin">Iniciar sesión ↗</a></nav></header>
    <main>
      <section className="hero"><div><p className="eyebrow">CONEXIONES QUE EMPIEZAN EN TU NEGOCIO</p><h1>Un toque.<br />Más cerca de<br /><em>tus clientes.</em></h1><p className="lead">De tu mostrador a tus reseñas, redes sociales o menú. Con Tappia, tus clientes acercan su celular o escanean el QR y llegan a donde tú quieras.</p><div className="actions"><a className="button" href={whatsapp}>Quiero mi Tappia ↗</a><a className="text-link" href="#como-funciona">Así funciona ↓</a></div><p className="small">Una placa. Un enlace que puedes actualizar.</p></div><figure><Image src="/images/tappia-placa.jpg" alt="Placa Tappia sobre un mostrador, con diseño para reseñas de Google, zona NFC y espacio para colocar el QR" width={1254} height={1254} priority sizes="(max-width: 760px) 100vw, 50vw" /><figcaption>Diseño de placa Tappia · El QR se personaliza para cada placa.</figcaption></figure></section>
      <section id="como-funciona" className="section"><p className="eyebrow">SIMPLE POR FUERA. CONECTADO POR DENTRO.</p><h2>Haz más fácil el siguiente paso.</h2><div className="feature-grid"><article><span>01 / CONECTA</span><h3>Acerca o escanea</h3><p>Coloca tu placa donde tus clientes puedan verla. Pueden abrir tu enlace con NFC o con la cámara de su celular.</p></article><article><span>02 / COMPARTE</span><h3>El destino lo eliges tú</h3><p>Reseñas, Instagram, menú o sitio web. Actualizamos el destino sin que tengas que cambiar el QR impreso.</p></article><article><span>03 / CONOCE</span><h3>Mira tus métricas</h3><p>Entra con tu cuenta y consulta las aperturas por día, semana, mes o año. Cada negocio tiene acceso a sus propios datos.</p></article></div></section>
      <section id="nosotros" className="about section"><p className="eyebrow">QUIÉNES SOMOS</p><h2>La conexión entre<br />tu espacio y tu mundo digital.</h2><div><p>En Tappia creamos herramientas para que los negocios compartan sus enlaces de forma sencilla, desde el lugar donde atienden a sus clientes.</p><p>Unimos placas QR y NFC con un panel de consulta. Nuestro propósito es quitar pasos: facilitar que una visita encuentre tus redes, consulte tu menú o comparta su experiencia.</p><a className="text-link" href={whatsapp}>Hablemos de tu negocio ↗</a></div></section>
      <section className="section faq"><p className="eyebrow">ANTES DE EMPEZAR</p><h2>Lo que necesitas saber.</h2><details><summary>¿Cada placa tiene un QR diferente?</summary><p>Sí. Cada placa tiene su propio enlace para identificar sus aperturas y cambiar su destino. El QR puede imprimirse en un sticker para colocarlo sobre la placa.</p></details><details><summary>¿Puedo cambiar el enlace después?</summary><p>Sí. El QR sigue apuntando a Tappia y el destino se actualiza desde la administración.</p></details><details><summary>¿Qué cuentan las métricas?</summary><p>Cuentan aperturas registradas del enlace, no personas únicas ni reseñas publicadas. Pueden incluir tus pruebas y accesos automatizados.</p></details></section>
      <section id="contacto" className="contact section"><p className="eyebrow">TU SIGUIENTE CONEXIÓN</p><h2>Tu negocio merece<br />su propia Tappia.</h2><p>Cuéntanos qué quieres compartir y te ayudamos a elegir el siguiente paso.</p><div className="actions"><a className="button" href={whatsapp}>Quiero mi Tappia · WhatsApp ↗</a><a href="mailto:emilioorozco232@gmail.com">Escríbenos por correo</a></div><p className="small">55 7880 6465 · emilioorozco232@gmail.com</p></section>
    </main><footer><a className="brand" href="/">tappia</a><span>Tu negocio, a un toque de distancia.</span><a href="/admin">Acceso a mi negocio ↗</a></footer>
  </div>;
}
